<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financial Report - {{ date('Y-m-d') }}</title>
    <link rel="stylesheet" href="{{ asset('css/dashboardview/reports/transactions_print.css') }}">
</head>
<body>
    <div class="no-print style-7002f9">
        <button onclick="window.print()" class="style-6c8947">Print Report</button>
        <button onclick="window.close()" class="style-2c7149">Close</button>
    </div>

    <div class="header">
        <div>
            <div class="logo">TaxiAdmin</div>
            <p class="style-a0b82d">Fleet Management System</p>
        </div>
        <div class="style-7851db">
            <h1 class="report-title">Financial Report</h1>
            <p class="style-70b282">Generated on: {{ date('Y-m-d H:i') }}</p>
        </div>
    </div>

    <div class="info">
        <p><strong>Report Period:</strong> All Time Records</p>
        <p><strong>Total Transactions:</strong> {{ $transactions->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Trip ID</th>
                <th>Driver</th>
                <th>Customer</th>
                <th>Total Fare</th>
                <th>Commission</th>
                <th>Net Driver</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php 
                $totalRevenue = 0; 
                $totalComm = 0;
            @endphp
            @foreach($transactions as $tx)
            <tr>
                <td>{{ $tx->created_at->format('Y-m-d') }}</td>
                <td>#TRP-{{ str_pad($tx->booking_id, 5, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $tx->driver->full_name ?? 'N/A' }}</td>
                <td>{{ $tx->customer->name ?? 'N/A' }}</td>
                <td>{{ number_format($tx->amount) }} MMK</td>
                <td>{{ number_format($tx->commission_amount) }} MMK</td>
                <td>{{ number_format($tx->driver_amount) }} MMK</td>
                <td class="status-completed">{{ $tx->status }}</td>
            </tr>
            @php 
                $totalRevenue += $tx->amount; 
                $totalComm += $tx->commission_amount;
            @endphp
            @endforeach
        </tbody>
    </table>

    <div class="summary-box">
        <div class="summary-item">
            <div class="summary-label">Total Revenue</div>
            <div class="summary-value">{{ number_format($totalRevenue) }} MMK</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Total Commission</div>
            <div class="summary-value style-f3ba20">{{ number_format($totalComm) }} MMK</div>
        </div>
    </div>

    <div class="footer">
        <p>Confidential Report - Generated by TaxiAdmin System</p>
        <p>&copy; {{ date('Y') }} TaxiAdmin. All rights reserved.</p>
    </div>

    <script>
        // Auto-open print dialog
        window.onload = function() {
            // window.print();
        }
    </script>
</body>
</html>
